name: Testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:      
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies for AT
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python
        pip install -Iv pillow==11.0.0
        pip install -Iv PyScreeze==1.0.1
        pip install -Iv pyautogui==0.9.54
        pip install pytest
        pip install behave
        
    - name: Run Acceptance tests for Ahorcado App
      run: |
        sudo apt-get update
        sudo apt-get install -y x11-xserver-utils
        touch ~/.Xauthority
        xauth generate :99 . trusted
        export DISPLAY=:99
        Xvfb :99 &
        behave features --junit
        #python -c "import pyautogui; pyautogui.screenshot('debug_screenshot.png')"
          
    - name: Upload Debug Screenshot
      uses: actions/upload-artifact@v4
      with:
        name: debug_screenshot
        path: debug_screenshot.png
